EDUCATIONAL_RULES = [
    {
        "target": "store_vars",
        "check": "name",
        "condition": "len(name) == 1 and name not in ['_', 'i', 'j', 'k']",
        "message": "Односимвольное имя переменной '{name}' (строки {lines})",
        "code": "EDU-VAR-001",
        "severity": "high",
    },
    {
        "target": "store_vars",
        "check": "name",
        "condition": "name in ['l', 'o', 'O']",
        "message": "Имя переменной '{name}' визуально похоже на цифру",
        "code": "EDU-VAR-002",
        "severity": "high",
    },
    {
        "target": "store_vars",
        "check": "name",
        "condition": "not name[0].isalpha() and name[0] != '_'",
        "message": "Имя переменной '{name}' должно начинаться с буквы или _",
        "code": "EDU-VAR-003",
        "severity": "medium",
    },
    {
        "target": "imports",
        "check": "name",
        "condition": "'re' == name",
        "message": "Запрещённый модуль 're' (регулярные выражения) в учебном задании",
        "code": "EDU-IMP-001",
        "severity": "medium",
    },
    {
        "target": "imports",
        "check": "name",
        "condition": "name in ['os', 'sys', 'subprocess']",
        "message": "Системные модули запрещены в учебном задании: {name}",
        "code": "EDU-IMP-002",
        "severity": "high",
    },
    {
        "target": "function_calls",
        "check": "name",
        "condition": "name in ['eval', 'exec', 'compile']",
        "message": "Опасная функция '{name}' запрещена",
        "code": "EDU-CALL-001",
        "severity": "critical",
    },
    {
        "target": "class_names",
        "check": "name",
        "condition": "not name[0].isupper()",
        "message": "Класс '{name}' должен начинаться с заглавной буквы (PEP 8)",
        "code": "EDU-CLS-001",
        "severity": "medium",
    },
    {
        "target": "genexp",
        "check": "absent",
        "condition": "True",
        "message": "Генераторные выражения запрещены в учебном задании",
        "code": "EDU-STRUCT-001",
        "severity": "high",
    },
    {
        "target": "lambda",
        "check": "absent",
        "condition": "True",
        "message": "Анонимные функции (lambda) запрещены",
        "code": "EDU-STRUCT-002",
        "severity": "medium",
    },
    {
        "target": "store_vars",
        "check": "name",
        "condition": "len(name) == 1",
        "message": "Односимвольное имя переменной '{name}' в строках {lines}",
        "code": "R001",
        "severity": "high",
    },
    {
        "target": "function_calls",
        "check": "name",
        "condition": "name in ['eval', 'exec']",
        "message": "Опасная функция: {name} (строки {lines})",
        "code": "R032",
        "severity": "critical",
    },
    {
        "target": "class_names",
        "check": "name",
        "condition": "not name[0].isupper()",
        "message": "Класс '{name}' должен начинаться с заглавной буквы",
        "code": "R011",
        "severity": "medium",
    },
    {
        "target": "load_vars",
        "check": "count",
        "condition": "count == 1",
        "message": "Переменная '{name}' используется только один раз (строка {lines})",
        "code": "R050",
        "severity": "low",
    },
    {
        "target": "genexp",
        "check": "absent",
        "condition": "True",
        "message": "Генераторные выражения запрещены",
        "code": "R031",
        "severity": "high",
    },
]
